AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is the main stack to deploy all resources in AWS'

Resources:
  SourceABucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-engineering-source-bucket
      # VersioningConfiguration:
      #   Status: Enabled
      # LifecycleConfiguration:
      #   Rules:
      #     - Id: LifeCycleRule1
      #       Status: Enabled
      #       Prefix: source_aws
      #       Transitions:
      #         - StorageClass: STANDARD_IA
      #           TransitionInDays: 30
      #         - StorageClass: GLACIER
      #           TransitionInDays: 90
      #       ExpirationInDays: 365

  GlueETLRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Glue_ETL_Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RoleAssumedByGlue
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action:
              - sts:AssumeRole
      # Policies:
      #   - PolicyName: ListBucketItems
      #     PolicyDocument:
      #       Version: '2012-10-17'
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - s3:ListBucket
      #             - s3:GetObject
      #           Resource:
      #             - !GetAtt SourceABucket.Arn
      #             - !Sub '${SourceABucket.Arn}/*'

  # SourceABucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref SourceABucket
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Sid: AllowRoleToAccessBucket
  #           Effect: Allow
  #           Principal:
  #             AWS: !GetAtt GlueETLRole.Arn
  #           Action:
  #             - s3:GetObject
  #             - s3:PutObject
  #           Resource:
  #             - !Sub '${SourceABucket.Arn}/*'

