AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main stack to deploy all resources in AWS'

Resources:
  SourceABucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-engineering-source-bucket
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: LifeCycleRule1
            Status: Enabled
            Prefix: source_aws
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 90
            ExpirationInDays: 365

  SourceBBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-engineering-destination-bucket
      VersioningConfiguration:
        Status: Enabled

  GlueETLRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Glue_ETL_Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RoleAssumedByGlue
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ListBucketItems
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt SourceABucket.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${SourceABucket.Arn}/*'
      ManagedPolicyArns:
        - !Ref S3BucketWritePolicy

  SourceABucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceABucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRoleToAccessBucket
            Effect: Allow
            Principal:
              AWS: !GetAtt GlueETLRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub '${SourceABucket.Arn}/*'

  S3BucketWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GluePermissionToWriteS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub '${SourceBBucket.Arn}/*'

  GlueStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./aws_glue_catalog.yml
      Parameters:
        pDestinationBucket: !Ref SourceBBucket
        pSourceBucket: !Ref SourceABucket
        pGlueETLRole: !Ref GlueETLRole

  GlueJobStack:
    Type: AWS::cloudformation::Stack
    Properties:
      TemplateURL: ./aws_glue_jobs.yml
      Parameters:
        pDestinationBucket: !Ref SourceBBucket
        pSourceBucket: !Ref SourceABucket
        pGlueETLRole: !Ref GlueETLRole

Outputs:
  oGlueEtlRole:
    Description: ARN of the Glue ETL Role
    Value: !GetAtt GlueETLRole.Arn

  oDestinationBucket:
    Description: name of the destination bucket
    Value: !Ref SourceBBucket
