AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Database and Tables for Curated Finance Data

Parameters:
  pDestinationBucket:
    Type: String
    Description: S3 bucket for curated data

Resources:
  FinanceDatabase:
    Type: AWS::Glue::Database
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: finance_curated
        Description: Database for storing curated finance data

  CustomersTable:
    Type: AWS::Glue::Table
    DependsOn: FinanceDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: finance_curated
      TableInput:
        Name: customers_table
        Description: Customer master data
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
        StorageDescriptor:
          Columns:
            - Name: customer_id
              Type: string
            - Name: first_name
              Type: string
            - Name: last_name
              Type: string
            - Name: date_of_birth
              Type: date
            - Name: email
              Type: string
            - Name: phone
              Type: string
          Location: !Sub s3://${pDestinationBucket}/customers
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

  AccountsTable:
    Type: AWS::Glue::Table
    DependsOn: FinanceDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: finance_curated
      TableInput:
        Name: accounts_table
        Description: Accounts data
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: csv
          typeOfData: file
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
        StorageDescriptor:
          Columns:
            - Name: account_id
              Type: string
            - Name: customer_id
              Type: string
            - Name: account_type
              Type: string
            - Name: open_date
              Type: date
            - Name: status
              Type: string
          Location: !Sub s3://${pDestinationBucket}/accounts_data
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Compressed: false
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
            Parameters:
              field.delim: ","

  PaymentsTable:
    Type: AWS::Glue::Table
    DependsOn: FinanceDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: finance_curated
      TableInput:
        Name: payments_table
        Description: Customer payments
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
        StorageDescriptor:
          Columns:
            - Name: payment_id
              Type: string
            - Name: customer_id
              Type: string
            - Name: amount
              Type: double
            - Name: payment_method
              Type: string
            - Name: payment_ts
              Type: timestamp
          Location: !Sub s3://${pDestinationBucket}/payments
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

Outputs:
  FinanceDatabaseName:
    Description: Glue database name
    Value: finance_curated
    Export:
      Name: FinanceDatabaseName
